# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.1.2
minecraft_version_range=>=26.1 <26.2
loader_version=0.18.5

# Dependencies
# check this on https://fabricmc.net/develop/
fabric_version=0.146.1+26.1.2
# https://modrinth.com/mod/yacl/versions
yacl_version=3.9.2+26.1-fabric
# https://modrinth.com/mod/modmenu/versions
modmenu_version=18.0.0-alpha.8
# https://modrinth.com/mod/fabric-language-kotlin/versions
kotlin_loader_version=1.13.10+kotlin.2.3.20