name: Publish Mod

on: [ pull_request, workflow_dispatch ]

env:
  MOD_VERSION: 0.1.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: |
            21
            25

      - name: Build All Versions
        run: bash ./gradlew buildAndCollect

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.G_TOKEN }}
          tag_name: ${{ env.MOD_VERSION }}
          name: ${{ env.MOD_VERSION }}
          files: build/libs/${{ env.MOD_VERSION }}/*.jar

      - name: Publish 26.2
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.M_TOKEN }}
          files: build/libs/${{ env.MOD_VERSION }}/garnet-${{ env.MOD_VERSION }}+26.2*.jar
          name: "${{ env.MOD_VERSION }}+26.2"
          version: "${{ env.MOD_VERSION }}+26.2"
          version-type: release
          loaders: fabric
          game-versions: "26.2"
          java: 25
          dependencies: |
            fabric-api
            modmenu
            yacl
